In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
data = pd.read_csv('train.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
datat = pd.read_csv('test.csv')
datat.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [4]:
frames=[data,datat]
data=pd.concat(frames) 
data

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,SaleType,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,NaN,3,1Fam,TA,No,706.0,0.0,...,WD,0,Pave,8,856.0,AllPub,0,2003,2003,2008
1,1262,0,0,NaN,3,1Fam,TA,Gd,978.0,0.0,...,WD,0,Pave,6,1262.0,AllPub,298,1976,1976,2007
2,920,866,0,NaN,3,1Fam,TA,Mn,486.0,0.0,...,WD,0,Pave,6,920.0,AllPub,0,2001,2002,2008
3,961,756,0,NaN,3,1Fam,Gd,No,216.0,0.0,...,WD,0,Pave,7,756.0,AllPub,0,1915,1970,2006
4,1145,1053,0,NaN,4,1Fam,TA,Av,655.0,0.0,...,WD,0,Pave,9,1145.0,AllPub,192,2000,2000,2008
5,796,566,320,NaN,1,1Fam,TA,No,732.0,0.0,...,WD,0,Pave,5,796.0,AllPub,40,1993,1995,2009
6,1694,0,0,NaN,3,1Fam,TA,Av,1369.0,0.0,...,WD,0,Pave,7,1686.0,AllPub,255,2004,2005,2007
7,1107,983,0,NaN,3,1Fam,TA,Mn,859.0,32.0,...,WD,0,Pave,7,1107.0,AllPub,235,1973,1973,2009
8,1022,752,0,NaN,2,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,8,952.0,AllPub,90,1931,1950,2008
9,1077,0,0,NaN,2,2fmCon,TA,No,851.0,0.0,...,WD,0,Pave,5,991.0,AllPub,0,1939,1950,2008
10,1040,0,0,NaN,3,1Fam,TA,No,906.0,0.0,...,WD,0,Pave,5,1040.0,AllPub,0,1965,1965,2008
11,1182,1142,0,NaN,4,1Fam,TA,No,998.0,0.0,...,New,0,Pave,11,1175.0,AllPub,147,2005,2006,2006
12,912,0,0,NaN,2,1Fam,TA,No,737.0,0.0,...,WD,176,Pave,4,912.0,AllPub,140,1962,1962,2008
13,1494,0,0,NaN,3,1Fam,TA,Av,0.0,0.0,...,New,0,Pave,7,1494.0,AllPub,160,2006,2007,2007
14,1253,0,0,NaN,2,1Fam,TA,No,733.0,0.0,...,WD,0,Pave,5,1253.0,AllPub,0,1960,1960,2008
15,854,0,0,NaN,2,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,5,832.0,AllPub,48,1929,2001,2007
16,1004,0,0,NaN,2,1Fam,TA,No,578.0,0.0,...,WD,0,Pave,5,1004.0,AllPub,0,1970,1970,2010
17,1296,0,0,NaN,2,Duplex,NaN,NaN,0.0,0.0,...,WD,0,Pave,6,0.0,AllPub,0,1967,1967,2006
18,1114,0,0,NaN,3,1Fam,TA,No,646.0,0.0,...,WD,0,Pave,6,1114.0,AllPub,0,2004,2004,2008
19,1339,0,0,NaN,3,1Fam,TA,No,504.0,0.0,...,COD,0,Pave,6,1029.0,AllPub,0,1958,1965,2009
20,1158,1218,0,NaN,4,1Fam,TA,Av,0.0,0.0,...,New,0,Pave,9,1158.0,AllPub,240,2005,2006,2006
21,1108,0,0,Grvl,3,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,6,637.0,AllPub,0,1930,1950,2007
22,1795,0,0,NaN,3,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,7,1777.0,AllPub,171,2002,2002,2008
23,1060,0,0,NaN,3,TwnhsE,TA,No,840.0,0.0,...,WD,0,Pave,6,1040.0,AllPub,100,1976,1976,2007
24,1060,0,0,NaN,3,1Fam,TA,Mn,188.0,668.0,...,WD,0,Pave,6,1060.0,AllPub,406,1968,2001,2010
25,1600,0,0,NaN,3,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,7,1566.0,AllPub,0,2007,2007,2009
26,900,0,0,NaN,3,1Fam,TA,Mn,234.0,486.0,...,WD,0,Pave,5,900.0,AllPub,222,1951,2000,2010
27,1704,0,0,NaN,3,1Fam,TA,No,1218.0,0.0,...,WD,0,Pave,7,1704.0,AllPub,0,2007,2008,2010
28,1600,0,0,NaN,2,1Fam,TA,Gd,1277.0,0.0,...,WD,0,Pave,6,1484.0,AllPub,288,1957,1997,2006
29,520,0,0,NaN,1,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,4,520.0,AllPub,49,1927,1950,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,641,0,0,NaN,2,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,4,641.0,AllPub,184,1925,1950,2006
1430,967,671,0,NaN,4,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,6,967.0,AllPub,0,1957,1957,2006
1431,729,0,0,NaN,2,1Fam,NaN,NaN,0.0,0.0,...,WD,0,Pave,5,0.0,AllPub,0,1945,1950,2006
1432,1060,336,0,NaN,4,2fmCon,TA,Mn,0.0,0.0,...,WD,0,Pave,8,660.0,AllPub,0,1951,1951,2006
1433,576,360,0,NaN,2,1Fam,Fa,No,0.0,0.0,...,WD,0,Grvl,6,216.0,AllPub,0,1916,1950,2006
1434,1778,0,0,NaN,2,TwnhsE,TA,Gd,1573.0,0.0,...,New,153,Pave,5,1573.0,AllPub,123,2005,2006,2006
1435,1646,0,0,NaN,2,TwnhsE,TA,Gd,1564.0,0.0,...,WD,155,Pave,5,1594.0,AllPub,128,2004,2005,2006
1436,1625,0,0,NaN,3,1Fam,TA,Gd,776.0,0.0,...,WD,0,Pave,6,1625.0,AllPub,136,1979,1979,2006
1437,1664,0,0,NaN,4,Duplex,TA,Mn,0.0,0.0,...,WD,0,Pave,10,1664.0,AllPub,0,1978,1978,2006
1438,1491,0,0,NaN,3,1Fam,TA,No,0.0,0.0,...,WD,0,Pave,7,1491.0,AllPub,120,2001,2001,2006
1439,1210,0,0,NaN,3,1Fam,TA,Av,576.0,0.0,...,WD,0,Pave,6,1128.0,AllPub,0,1975,1975,2006
1440,1650,0,0,NaN,2,1Fam,TA,Gd,909.0,0.0,...,WD,138,Pave,6,1632.0,AllPub,0,1958,1958,2006
1441,1403,0,0,NaN,2,1Fam,TA,Av,1136.0,116.0,...,WD,0,Pave,5,1381.0,AllPub,0,2000,2000,2006
1442,1960,0,0,NaN,3,1Fam,Gd,Av,1350.0,0.0,...,New,0,Pave,8,1728.0,AllPub,172,2005,2006,2006
1443,1838,0,0,NaN,3,1Fam,TA,Gd,1455.0,0.0,...,New,0,Pave,9,1838.0,AllPub,161,2005,2006,2006
1444,1600,0,0,NaN,3,1Fam,NaN,NaN,0.0,0.0,...,WD,0,Pave,6,0.0,AllPub,0,1951,1951,2006
1445,1368,0,0,NaN,2,Duplex,TA,Gd,1243.0,0.0,...,WD,0,Pave,8,1288.0,AllPub,0,1997,1997,2006
1446,616,688,0,NaN,3,TwnhsE,TA,Mn,0.0,0.0,...,WD,0,Pave,5,264.0,AllPub,141,1977,1977,2006
1447,874,0,0,NaN,3,1Fam,TA,No,441.0,0.0,...,WD,0,Pave,5,864.0,AllPub,0,1968,2003,2006
1448,1652,0,0,NaN,4,Duplex,TA,No,149.0,0.0,...,WD,0,Pave,8,1652.0,AllPub,0,1970,1970,2006
1449,630,0,0,NaN,1,Twnhs,TA,Av,522.0,0.0,...,WD,0,Pave,3,630.0,AllPub,0,1970,1970,2006
1450,546,546,0,NaN,3,TwnhsE,TA,No,252.0,0.0,...,WD,0,Pave,5,546.0,AllPub,0,1972,1972,2006
1451,1360,0,0,NaN,3,1Fam,TA,Av,119.0,344.0,...,WD,0,Pave,8,1104.0,AllPub,160,1969,1979,2006
1452,546,546,0,NaN,3,Twnhs,TA,No,408.0,0.0,...,WD,0,Pave,5,546.0,AllPub,0,1970,1970,2006
1453,546,546,0,NaN,3,Twnhs,TA,No,0.0,0.0,...,WD,0,Pave,5,546.0,AllPub,0,1970,1970,2006
1454,546,546,0,NaN,3,Twnhs,TA,No,0.0,0.0,...,WD,0,Pave,5,546.0,AllPub,0,1970,1970,2006
1455,546,546,0,NaN,3,TwnhsE,TA,No,252.0,0.0,...,WD,0,Pave,6,546.0,AllPub,0,1970,1970,2006
1456,1224,0,0,NaN,4,1Fam,TA,No,1224.0,0.0,...,WD,0,Pave,7,1224.0,AllPub,474,1960,1996,2006
1457,970,0,0,NaN,3,1Fam,TA,Av,337.0,0.0,...,WD,0,Pave,6,912.0,AllPub,80,1992,1992,2006
1458,996,1004,0,NaN,3,1Fam,TA,Av,758.0,0.0,...,WD,0,Pave,9,996.0,AllPub,190,1993,1994,2006

In [5]:
data.set_index('Id',inplace=True)

In [6]:
for i in data.columns:
    if data[i].dtypes == 'object':#lotShape,HouseStyle,Condition1
        print (data[i].value_counts()) #SaleType , MiscFeatu,Fence,GarageCond/Qual,FireplaceQu,KitchenQual,CentralAir,BsmtFinType2,type1,BsmtQual,ExterQual,RoofStyle,

Grvl    120
Pave     78
Name: Alley, dtype: int64
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: BldgType, dtype: int64
TA    2606
Gd     122
Fa     104
Po       5
Name: BsmtCond, dtype: int64
No    1904
Av     418
Gd     276
Mn     239
Name: BsmtExposure, dtype: int64
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: BsmtFinType1, dtype: int64
Unf    2493
Rec     105
LwQ      87
BLQ      68
ALQ      52
GLQ      34
Name: BsmtFinType2, dtype: int64
TA    1283
Gd    1209
Ex     258
Fa      88
Name: BsmtQual, dtype: int64
Y    2723
N     196
Name: CentralAir, dtype: int64
Norm      2511
Feedr      164
Artery      92
RRAn        50
PosN        39
RRAe        28
PosA        20
RRNn         9
RRNe         6
Name: Condition1, dtype: int64
Norm      2889
Feedr       13
Artery       5
PosN         4
PosA         4
RRNn         2
RRAn         1
RRAe         1
Name: Condition2, dtype: int64
SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: Electrical, dtype: int64
TA    2538
Gd     299
Fa      67
Ex      12
Po       3
Name: ExterCond, dtype: int64
TA    1798
Gd     979
Ex     107
Fa      35
Name: ExterQual, dtype: int64
VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
CBlock        2
Stone         2
ImStucc       1
Name: Exterior1st, dtype: int64
VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Name: Exterior2nd, dtype: int64
MnPrv    329
GdPrv    118
GdWo     112
MnWw      12
Name: Fence, dtype: int64
Gd    744
TA    592
Fa     74
Po     46
Ex     43
Name: FireplaceQu, dtype: int64
PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: Foundation, dtype: int64
Typ     2717
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Name: Functional, dtype: int64
TA    2654
Fa      74
Gd      15
Po      14
Ex       3
Name: GarageCond, dtype: int64
Unf    1230
RFn     811
Fin     719
Name: GarageFinish, dtype: int64
TA    2604
Fa     124
Gd      24
Po       5
Ex       3
Name: GarageQual, dtype: int64
Attchd     1723
Detchd      779
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64
GasA     2874
GasW       27
Grav        9
Wall        6
OthW        2
Floor       1
Name: Heating, dtype: int64
Ex    1493
TA     857
Gd     474
Fa      92
Po       3
Name: HeatingQC, dtype: int64
1Story    1471
2Story     872
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: HouseStyle, dtype: int64
TA    1492
Gd    1151
Ex     205
Fa      70
Name: KitchenQual, dtype: int64
Lvl    2622
HLS     120
Bnk     117
Low      60
Name: LandContour, dtype: int64
Gtl    2778
Mod     125
Sev      16
Name: LandSlope, dtype: int64
Inside     2133
Corner      511
CulDSac     176
FR2          85
FR3          14
Name: LotConfig, dtype: int64
Reg    1859
IR1     968
IR2      76
IR3      16
Name: LotShape, dtype: int64
RL         2265
RM          460
FV          139
RH           26
C (all)      25
Name: MSZoning, dtype: int64
None       1742
BrkFace     879
Stone       249
BrkCmn       25
Name: MasVnrType, dtype: int64
Shed    95
Gar2     5
Othr     4
TenC     1
Name: MiscFeature, dtype: int64
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Name: Neighborhood, dtype: int64
Y    2641
N     216
P      62
Name: PavedDrive, dtype: int64
Ex    4
Gd    4
Fa    2
Name: PoolQC, dtype: int64
CompShg    2876
Tar&Grv      23
WdShake       9
WdShngl       7
Metal         1
Membran       1
ClyTile       1
Roll          1
Name: RoofMatl, dtype: int64
Gable      2310
Hip         551
Gambrel      22
Flat         20
Mansard      11
Shed          5
Name: RoofStyle, dtype: int64
Normal     2402
Partial     245
Abnorml     190
Family       46
Alloca       24
AdjLand      12
Name: SaleCondition, dtype: int64
WD       2525
New       239
COD        87
ConLD      26
CWD        12
ConLI       9
ConLw       8
Oth         7
Con         5
Name: SaleType, dtype: int64
Pave    2907
Grvl      12
Name: Street, dtype: int64
AllPub    2916
NoSeWa       1
Name: Utilities, dtype: int64

In [7]:
data.select_dtypes(include=['object']).isnull().sum()

Alley            2721
BldgType            0
BsmtCond           82
BsmtExposure       82
BsmtFinType1       79
BsmtFinType2       80
BsmtQual           81
CentralAir          0
Condition1          0
Condition2          0
Electrical          1
ExterCond           0
ExterQual           0
Exterior1st         1
Exterior2nd         1
Fence            2348
FireplaceQu      1420
Foundation          0
Functional          2
GarageCond        159
GarageFinish      159
GarageQual        159
GarageType        157
Heating             0
HeatingQC           0
HouseStyle          0
KitchenQual         1
LandContour         0
LandSlope           0
LotConfig           0
LotShape            0
MSZoning            4
MasVnrType         24
MiscFeature      2814
Neighborhood        0
PavedDrive          0
PoolQC           2909
RoofMatl            0
RoofStyle           0
SaleCondition       0
SaleType            1
Street              0
Utilities           2
dtype: int64

In [8]:
for i in data.columns:
    if data[i].dtypes=='object':
        data[i]=data[i].fillna('Missing')

In [9]:
data.select_dtypes(include=['object']).isnull().sum()

Alley            0
BldgType         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinType2     0
BsmtQual         0
CentralAir       0
Condition1       0
Condition2       0
Electrical       0
ExterCond        0
ExterQual        0
Exterior1st      0
Exterior2nd      0
Fence            0
FireplaceQu      0
Foundation       0
Functional       0
GarageCond       0
GarageFinish     0
GarageQual       0
GarageType       0
Heating          0
HeatingQC        0
HouseStyle       0
KitchenQual      0
LandContour      0
LandSlope        0
LotConfig        0
LotShape         0
MSZoning         0
MasVnrType       0
MiscFeature      0
Neighborhood     0
PavedDrive       0
PoolQC           0
RoofMatl         0
RoofStyle        0
SaleCondition    0
SaleType         0
Street           0
Utilities        0
dtype: int64

In [10]:
data.select_dtypes(exclude='object').isnull().sum()

1stFlrSF            0
2ndFlrSF            0
3SsnPorch           0
BedroomAbvGr        0
BsmtFinSF1          1
BsmtFinSF2          1
BsmtFullBath        2
BsmtHalfBath        2
BsmtUnfSF           1
EnclosedPorch       0
Fireplaces          0
FullBath            0
GarageArea          1
GarageCars          1
GarageYrBlt       159
GrLivArea           0
HalfBath            0
KitchenAbvGr        0
LotArea             0
LotFrontage       486
LowQualFinSF        0
MSSubClass          0
MasVnrArea         23
MiscVal             0
MoSold              0
OpenPorchSF         0
OverallCond         0
OverallQual         0
PoolArea            0
SalePrice        1459
ScreenPorch         0
TotRmsAbvGrd        0
TotalBsmtSF         1
WoodDeckSF          0
YearBuilt           0
YearRemodAdd        0
YrSold              0
dtype: int64

In [11]:
from sklearn.preprocessing import Imputer

In [12]:
cols = ['TotalBsmtSF','MasVnrArea','LotFrontage','GarageYrBlt' ,'GarageCars','GarageArea','BsmtFinSF1','BsmtFinSF2','BsmtFullBath','BsmtHalfBath','BsmtUnfSF']
im=Imputer(missing_values='NaN', strategy='mean',axis=0)
for x in cols:
    imputer=im.fit(data[x].reshape(-1, 1))
    data[x]=imputer.transform(data[x].reshape(-1, 1))

/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  after removing the cwd from sys.path.
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """

In [13]:
data.select_dtypes(exclude='object').isnull().sum()

1stFlrSF            0
2ndFlrSF            0
3SsnPorch           0
BedroomAbvGr        0
BsmtFinSF1          0
BsmtFinSF2          0
BsmtFullBath        0
BsmtHalfBath        0
BsmtUnfSF           0
EnclosedPorch       0
Fireplaces          0
FullBath            0
GarageArea          0
GarageCars          0
GarageYrBlt         0
GrLivArea           0
HalfBath            0
KitchenAbvGr        0
LotArea             0
LotFrontage         0
LowQualFinSF        0
MSSubClass          0
MasVnrArea          0
MiscVal             0
MoSold              0
OpenPorchSF         0
OverallCond         0
OverallQual         0
PoolArea            0
SalePrice        1459
ScreenPorch         0
TotRmsAbvGrd        0
TotalBsmtSF         0
WoodDeckSF          0
YearBuilt           0
YearRemodAdd        0
YrSold              0
dtype: int64

In [14]:
data.shape

(2919, 80)

In [15]:
data['SaleCondition'] = ['Normal' if x == 'Normal'  else 'Other' for x in data['SaleCondition']]

print(data['SaleCondition'].value_counts().sort_values(ascending=False))

Normal    2402
Other      517
Name: SaleCondition, dtype: int64

In [16]:
data['SaleType'] = ['WD' if x == 'WD'  else 'Other' for x in data['SaleType']]

print(data['SaleType'].value_counts().sort_values(ascending=False))

WD       2525
Other     394
Name: SaleType, dtype: int64

In [17]:
data['PavedDrive'] = ['Y' if x == 'Y'  else 'Other' for x in data['PavedDrive']]

print(data['PavedDrive'].value_counts().sort_values(ascending=False))

Y        2641
Other     278
Name: PavedDrive, dtype: int64

In [18]:
data['MiscFeature'] = ['Missing' if x == 'Missing'  else 'Known' for x in data['MiscFeature']]

print(data['MiscFeature'].value_counts().sort_values(ascending=False))

Missing    2814
Known       105
Name: MiscFeature, dtype: int64

In [19]:
data['LotShape'] = ['Reg' if x == 'Reg'  else 'IR' for x in data['LotShape']]

print(data['LotShape'].value_counts().sort_values(ascending=False))

Reg    1859
IR     1060
Name: LotShape, dtype: int64

In [20]:
data['LotShape'] = ['Reg' if x == 'Reg'  else 'IR' for x in data['LotShape']]

print(data['LotShape'].value_counts().sort_values(ascending=False))
data['LandContour'] = ['Lvl' if x == 'Lvl'  else 'Other' for x in data['LandContour']]

print(data['LandContour'].value_counts().sort_values(ascending=False))
data['Condition1'] = ['Norm' if x == 'Norm'  else 'Other' for x in data['Condition1']]
data['Condition2'] = ['Norm' if x == 'Norm'  else 'Other' for x in data['Condition2']]
print(data['Condition1'].value_counts().sort_values(ascending=False))
data['RoofStyle'] = ['Gable' if x == 'Gable'  else 'Other' for x in data['RoofStyle']]
data['GarageQual'] = ['TA' if x == 'TA'  else 'Other' for x in data['GarageQual']]
#RoofMatl
data['RoofMatl'] = ['CompShg' if x == 'CompShg'  else 'Other' for x in data['RoofMatl']]
data['ExterCond'] = ['TA' if x == 'TA'  else 'Other' for x in data['ExterCond']]
data['BsmtCond'] = ['TA' if x == 'TA'  else 'Other' for x in data['BsmtCond']]
data['BsmtFinType2'] = ['Unf' if x == 'Unf'  else 'Other' for x in data['BsmtFinType2']]
data['Heating'] = ['GasB' if x == 'GasB'  else 'Other' for x in data['Heating']]
data['Electrical'] = ['SBrkr' if x == 'SBrkr'  else 'Other' for x in data['Electrical']]
data['Functional'] = ['Typ' if x == 'Typ'  else 'Other' for x in data['Functional']]
data['GarageCond'] = ['TA' if x == 'TA'  else 'Other' for x in data['GarageCond']]

Reg    1859
IR     1060
Name: LotShape, dtype: int64
Lvl      2622
Other     297
Name: LandContour, dtype: int64
Norm     2511
Other     408
Name: Condition1, dtype: int64

In [21]:
for i in data.columns:
    if data[i].dtypes == 'object':#lotShape,HouseStyle,Condition1
        print (data[i].value_counts()) #SaleType , MiscFeatu,Fence,GarageCond/Qual,FireplaceQu,KitchenQual,CentralAir,BsmtFinType2,type1,BsmtQual,ExterQual,RoofStyle,

Missing    2721
Grvl        120
Pave         78
Name: Alley, dtype: int64
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: BldgType, dtype: int64
TA       2606
Other     313
Name: BsmtCond, dtype: int64
No         1904
Av          418
Gd          276
Mn          239
Missing      82
Name: BsmtExposure, dtype: int64
Unf        851
GLQ        849
ALQ        429
Rec        288
BLQ        269
LwQ        154
Missing     79
Name: BsmtFinType1, dtype: int64
Unf      2493
Other     426
Name: BsmtFinType2, dtype: int64
TA         1283
Gd         1209
Ex          258
Fa           88
Missing      81
Name: BsmtQual, dtype: int64
Y    2723
N     196
Name: CentralAir, dtype: int64
Norm     2511
Other     408
Name: Condition1, dtype: int64
Norm     2889
Other      30
Name: Condition2, dtype: int64
SBrkr    2671
Other     248
Name: Electrical, dtype: int64
TA       2538
Other     381
Name: ExterCond, dtype: int64
TA    1798
Gd     979
Ex     107
Fa      35
Name: ExterQual, dtype: int64
VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
CBlock        2
Stone         2
ImStucc       1
Missing       1
Name: Exterior1st, dtype: int64
VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
Stucco       47
BrkFace      47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Missing       1
Name: Exterior2nd, dtype: int64
Missing    2348
MnPrv       329
GdPrv       118
GdWo        112
MnWw         12
Name: Fence, dtype: int64
Missing    1420
Gd          744
TA          592
Fa           74
Po           46
Ex           43
Name: FireplaceQu, dtype: int64
PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: Foundation, dtype: int64
Typ      2717
Other     202
Name: Functional, dtype: int64
TA       2654
Other     265
Name: GarageCond, dtype: int64
Unf        1230
RFn         811
Fin         719
Missing     159
Name: GarageFinish, dtype: int64
TA       2604
Other     315
Name: GarageQual, dtype: int64
Attchd     1723
Detchd      779
BuiltIn     186
Missing     157
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64
Other    2919
Name: Heating, dtype: int64
Ex    1493
TA     857
Gd     474
Fa      92
Po       3
Name: HeatingQC, dtype: int64
1Story    1471
2Story     872
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: HouseStyle, dtype: int64
TA         1492
Gd         1151
Ex          205
Fa           70
Missing       1
Name: KitchenQual, dtype: int64
Lvl      2622
Other     297
Name: LandContour, dtype: int64
Gtl    2778
Mod     125
Sev      16
Name: LandSlope, dtype: int64
Inside     2133
Corner      511
CulDSac     176
FR2          85
FR3          14
Name: LotConfig, dtype: int64
Reg    1859
IR     1060
Name: LotShape, dtype: int64
RL         2265
RM          460
FV          139
RH           26
C (all)      25
Missing       4
Name: MSZoning, dtype: int64
None       1742
BrkFace     879
Stone       249
BrkCmn       25
Missing      24
Name: MasVnrType, dtype: int64
Missing    2814
Known       105
Name: MiscFeature, dtype: int64
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Name: Neighborhood, dtype: int64
Y        2641
Other     278
Name: PavedDrive, dtype: int64
Missing    2909
Ex            4
Gd            4
Fa            2
Name: PoolQC, dtype: int64
CompShg    2876
Other        43
Name: RoofMatl, dtype: int64
Gable    2310
Other     609
Name: RoofStyle, dtype: int64
Normal    2402
Other      517
Name: SaleCondition, dtype: int64
WD       2525
Other     394
Name: SaleType, dtype: int64
Pave    2907
Grvl      12
Name: Street, dtype: int64
AllPub     2916
Missing       2
NoSeWa        1
Name: Utilities, dtype: int64

In [22]:
data['MSZoning'] = ['RL' if x == 'RL'  else 'Other' for x in data['MSZoning']]

In [23]:
data.drop(['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'], axis = 1, inplace = True)

In [24]:
to_dummylist=[]
for x in data.columns:
    if data[x].dtypes=='object':
        to_dummylist.append(x)
print (to_dummylist)

['BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1', 'Condition2', 'Electrical', 'ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd', 'Foundation', 'Functional', 'GarageCond', 'GarageFinish', 'GarageQual', 'GarageType', 'Heating', 'HeatingQC', 'HouseStyle', 'KitchenQual', 'LandContour', 'LandSlope', 'LotConfig', 'LotShape', 'MSZoning', 'MasVnrType', 'Neighborhood', 'PavedDrive', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType', 'Street', 'Utilities']

In [25]:
def dummy_df(df, to_dummylist):
    for x in to_dummylist:
        dummies = pd.get_dummies(df[x], prefix=x, dummy_na=False)
        df = df.drop(x, 1)
        df = pd.concat([df, dummies], axis=1)
    return df

In [26]:
X=data.drop(labels='SalePrice',axis=1)
X = dummy_df(X, to_dummylist)
print(X.head(5))

    1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
Id
1        856       854          0             3       706.0         0.0
2       1262         0          0             3       978.0         0.0
3        920       866          0             3       486.0         0.0
4        961       756          0             3       216.0         0.0
5       1145      1053          0             4       655.0         0.0

    BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch        ...         \
Id                                                              ...
1            1.0           0.0      150.0              0        ...
2            0.0           1.0      284.0              0        ...
3            1.0           0.0      434.0              0        ...
4            1.0           0.0      540.0            272        ...
5            1.0           0.0      490.0              0        ...

    RoofStyle_Other  SaleCondition_Normal  SaleCondition_Other  \
Id
1                 0                     1                    0
2                 0                     1                    0
3                 0                     1                    0
4                 0                     0                    1
5                 0                     1                    0

    SaleType_Other  SaleType_WD  Street_Grvl  Street_Pave  Utilities_AllPub  \
Id
1                0            1            0            1                 1
2                0            1            0            1                 1
3                0            1            0            1                 1
4                0            1            0            1                 1
5                0            1            0            1                 1

    Utilities_Missing  Utilities_NoSeWa
Id
1                   0                 0
2                   0                 0
3                   0                 0
4                   0                 0
5                   0                 0

[5 rows x 210 columns]

In [27]:
#Data Preprocessing 
from sklearn.preprocessing import StandardScaler
#making a pipeline 
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression , ElasticNet, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
pipe={
    'Enet':make_pipeline(StandardScaler(),ElasticNet()),
       'ridge':make_pipeline(StandardScaler(),Ridge()),
       'lasso':make_pipeline(StandardScaler(),Lasso()),
    'rf':make_pipeline(StandardScaler(), RandomForestRegressor()),
    'gb':make_pipeline(StandardScaler(), GradientBoostingRegressor())
}     
pipe1={'Linear':make_pipeline(StandardScaler(),LinearRegression),}

In [28]:
#Checking the pipe 
for key , values in pipe.items():
    print(key , type(values))

Enet <class 'sklearn.pipeline.Pipeline'>
ridge <class 'sklearn.pipeline.Pipeline'>
lasso <class 'sklearn.pipeline.Pipeline'>
rf <class 'sklearn.pipeline.Pipeline'>
gb <class 'sklearn.pipeline.Pipeline'>

In [29]:
#Decalring the hyperparameters 
lasso_hyperparameters = { 'lasso__alpha' : [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10] }
ridge_hyperparameters = { 'ridge__alpha': [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10] }
enet_hyperparameters = { 'elasticnet__alpha': [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10], 
                       'elasticnet__l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]}
rf_hyperparameters = { 
    'randomforestregressor__n_estimators' : [100, 200],
    'randomforestregressor__max_features': ['auto', 'sqrt', 0.33],
}
gb_hyperparameters = { 'gradientboostingregressor__n_estimators': [100, 200],
                     'gradientboostingregressor__learning_rate': [0.05, 0.1, 0.2],
                     'gradientboostingregressor__max_depth': [1, 3, 5]}

In [30]:
#Creating hyperparameters Dictionary 
hyperparameters={
    'lasso' : lasso_hyperparameters,
    'ridge' : ridge_hyperparameters,
    'Enet' : enet_hyperparameters,
    'rf' : rf_hyperparameters,
    'gb' : gb_hyperparameters
}

In [31]:
y=data['SalePrice']
y_train=y[:1460]
X_train=X[:1460]
X_test=X[1460:]

In [32]:
#Fit and Tune using cross-validation 
fitted_models = {}
# Helper for cross-validation
from sklearn.model_selection import GridSearchCV
for name , pipeline in pipe.items():
    model = GridSearchCV(pipeline , hyperparameters[name] ,cv =10 ,n_jobs=-1)
    model.fit(X_train,np.log(y_train))
    fitted_models[name]=model
    print(name, 'has been fitted.')

/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/media/akki/0C77C1DB5023617A/Downloads/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

Enet has been fitted.
ridge has been fitted.
lasso has been fitted.
rf has been fitted.
gb has been fitted.

In [33]:
#Evalute the model 
for name, model in fitted_models.items():
    print(name, model.best_score_)#r2-values

Enet 0.8728820988603424
ridge 0.8648082367394867
lasso 0.8711964141687648
rf 0.881013821483755
gb 0.9010856469218617

In [34]:
#Evalute the model 
for name, model in fitted_models.items():
    if name == 'gb':
        lists=model.predict(X_test)#r2-values
print (lists)

[11.68815619 11.94542201 12.13632693 ... 11.9086231  11.64766743
 12.35341026]

In [35]:
lists=np.exp(lists)
lists

array([119152.10992822, 154110.01578365, 186526.1895925 , ...,
       148542.01034344, 114424.14862405, 231749.02028757])

In [36]:
df = pd.DataFrame(lists)
df

                  0
0     119152.109928
1     154110.015784
2     186526.189593
3     190297.177933
4     186310.789640
5     175565.855276
6     174074.884625
7     169087.674550
8     184290.796892
9     123976.655357
10    196411.659166
11     95956.761061
12     96127.502763
13    153914.638324
14    134424.113153
15    403278.305200
16    254654.996856
17    298312.684658
18    268954.142523
19    473435.111650
20    323801.154226
21    203832.108925
22    163052.553926
23    169148.900234
24    173825.051135
25    188385.044480
26    358025.296214
27    238066.219877
28    207747.381364
29    215049.445600
...             ...
1429   77297.357567
1430  130000.175727
1431   51222.038357
1432   97204.972064
1433   56283.054417
1434  281785.381748
1435  278223.506651
1436  194768.205138
1437  147716.247245
1438  223187.192159
1439  158610.588877
1440  203693.698976
1441  188112.522237
1442  332415.355974
1443  356064.746313
1444   90201.942794
1445  216033.413180
1446  110707.400607
1447  135434.441287
1448  140960.283417
1449   81709.083535
1450   77077.097441
1451  145416.064135
1452   85797.657778
1453   73519.939358
1454   78365.985672
1455   84935.136754
1456  148542.010343
1457  114424.148624
1458  231749.020288

[1459 rows x 1 columns]

In [37]:
df.to_csv('example5.csv')